mlp_config = {
    'views_dims': [250, 250],
    "save_dir": "./experiments/synthetic/",
    "hidden_dims": [100, 100], 
    "output_dim": 2, 
    "batch_norm": True, 
    "dropout": True, 
    "activation": "relu", 
    "learning_rate": 1e-3, 
    "batch_size": 100,  
    "weight_decay": 1e-4,
    "patience":7,
    "delta":0.0,
    "epoch": 50,
    "lr_decay": 0.99,
    "optimizer": 'Adam',
    "early_stop": False,
    "bestmodel": True,
    "experiment_no": 0,
    "track": False,
}
