_target_: hydra_plugins.hydra_optuna_sweeper.OptunaSweeper

direction: maximize
n_trials: 20

sampler:
  _target_: optuna.samplers.TPESampler
  seed: 0

params:
  model.learning_rate:
    distribution: loguniform
    low: 1e-4
    high: 1e-2

  model.s_lam:
    distribution: uniform
    low: 0.01
    high: 1.0

  model.ns_alpha:
    distribution: uniform
    low: 0.0
    high: 0.5
